<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 09 Aug 2017 10:37:13 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'மன்ற அறிவிப்பு';
$l['announcements'] = 'அறிவிப்பு';
$l['forum_announcement'] = 'மன்ற அறிவிப்பு: {1}';
$l['error_invalidannouncement'] = 'குறிப்பிட்ட அறிவிப்பு செல்லுபடியாகாதது';
$l['announcement_edit'] = 'இந்த அறிவிப்பை திருத்து';
$l['announcement_qdelete'] = 'இந்த அறிவிப்பை நீக்கு';
$l['announcement_quickdelete_confirm'] = 'இந்த அறிவிப்பை நீக்க கட்டாயம்  வேண்டுகிறீர்களா??';
