<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 05:34:54 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'முழு பதிப்பு:';
$l['archive_replies'] = 'பதில்கள்';
$l['archive_reply'] = 'பதில்';
$l['archive_pages'] = 'பக்கங்கள்:';
$l['archive_note'] = 'நீங்கள் தற்போது நமது உள்ளடக்கத்தின் சுருக்கப்பட்ட பதிப்பை காண்கிறீர்கள்  <a href=\\"{1}\\">முழு பதிப்பை</a> சரியான வடிவமைத்தலுடன காணலாம்';
$l['archive_nopermission'] = 'மன்னிக்கவும்,இந்த வளத்தை காண உங்களுக்கு அனுமதியில்லை.';
$l['error_nothreads'] = 'தற்போது இந்த மன்றத்தில் இழைகள் ஏதுமில்லை';
$l['error_nopermission'] = 'இந்த மன்றத்தில் உள்ள இழைகளை காண உங்களுக்கு அனுமதியில்லை.';
$l['error_unapproved_thread'] = 'இந்த இழை அங்கீகரிக்கபடாதது. இழையின் உள்ளடக்கத்தை காண <a href=\\"{1}\\">முழு பதிப்பை </a> காணவும்';
$l['archive_not_found'] = 'வேண்டிய பக்கம் சேவையகத்தில் கிடைக்கவில்லை.';
$l['error_mustlogin'] = 'இந்த கலந்துரையாடல் மன்றம்  அனைத்து பயனர்களை உள்நுழைய வேண்டுகிறது.';
