<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Fri, 29 Sep 2017 22:53:05 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'எம்மை தொடர்புகொள்க';
$l['contact_no_message'] = 'நீங்கள் அனுப்புவதற்கு ஒரு விடுகையை கொடுக்கவில்லை.';
$l['contact_no_subject'] = 'நீங்கள் விடுகையின் பொருளை கொடுக்க வேண்டியுள்ளது.';
$l['contact_no_email'] = 'நீங்கள் ஒரு செல்லுபடியான மின்னஞ்சல் முகவரியை கொடுக்க வேண்டியுள்ளது.';
$l['contact_success_message'] = 'உங்களது விடுகை வெற்றிகரமாக  நிர்வாகிக்கு அனுப்பப்பட்டது.';
$l['contact_subject'] = 'பொருள்';
$l['contact_subject_desc'] = 'விடுகை தலைப்பின் சுருக்கத்தை கொடுக்கவும்.';
$l['contact_message'] = 'விடுகை';
$l['contact_message_desc'] = 'உங்களது விடுகையை விலாவரியாக விவரிக்கவும்.';
$l['contact_email'] = 'மின்னஞ்சல்';
$l['contact_email_desc'] = 'நீங்கள் உங்களை தொடர்பு கொள்ள ஒரு மின்னஞ்சல் முகவரியை கொடுக்கவும்.';
$l['contact_send'] = 'அனுப்பு';
$l['subject_too_long'] = 'பொருள் அளவைவிட மிகநீளமாக உள்ளது. தயவுசெய்து விடுகையை  {1} வார்த்தைகளுக்கு அதிகமாக எழுதவும் (தற்சமயம் {2}).';
$l['message_too_short'] = 'விடுகை அளவைவிட மிகநீளமாக உள்ளது. தயவுசெய்து விடுகையை  {1} வார்த்தைகளுக்கு அதிகமாக எழுதவும் (தற்சமயம் {2}).';
$l['message_too_long'] = 'விடுகை அளவைவிட குறைவாகவுள்ளது. தயவுசெய்து விடுகையை  {1} வார்த்தைகளுக்கு குறைவாக எழுதவும் (தற்சமயம் {2}).';
$l['error_stop_forum_spam_spammer'] = 'மன்னிக்கவும், {1} ஒரு எரித-பரப்பாளர் உடன் ஒத்திருப்பதால் உங்களது தொடர்பு சமர்ப்பித்தல் முடக்கப்பட்டுள்ளது.';
$l['error_stop_forum_spam_fetching'] = 'உங்கள் விடுகையை எரித தரவுத்தளத்தில் சரிபார்ப்பதில் ஏதேனும் பிழை ஏற்பட்டுள்ளது. தரவுத்தளத்தை அணுக முடியவில்லை என்பது போல் உள்ளது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.';
