<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Fri, 25 Aug 2017 13:01:44 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'எம்மை தொடர்புகொள்க';
$l['contact_no_message'] = 'நீங்கள் அனுப்புவதற்கு ஒரு விடுகையை கொடுக்கவில்லை.';
$l['contact_no_subject'] = 'நீங்கள் விடுகையின் பொருளை கொடுக்க வேண்டியுள்ளது.';
$l['contact_no_email'] = 'நீங்கள் ஒரு செல்லுபடியான மின்னஞ்சல் முகவரியை கொடுக்க வேண்டியுள்ளது.';
$l['contact_success_message'] = 'உங்களது விடுகை வெற்றிகரமாக  நிர்வாகிக்கு அனுப்பப்பட்டது.';
$l['contact_subject'] = 'பொருள்';
$l['contact_subject_desc'] = 'விடுகை தலைப்பின் சுருக்கத்தை கொடுக்கவும்.';
$l['contact_message'] = 'விடுகை';
$l['contact_message_desc'] = 'உங்களது விடுகையை விலாவரியாக விவரிக்கவும்.';
$l['contact_email'] = 'மின்னஞ்சல்';
$l['contact_email_desc'] = 'நீங்கள் உங்களை தொடர்பு கொள்ள ஒரு மின்னஞ்சல் முகவரியை கொடுக்கவும்.';
$l['contact_send'] = 'அனுப்பு';
$l['subject_too_long'] = '';
$l['message_too_short'] = '';
$l['message_too_long'] = '';
$l['error_stop_forum_spam_spammer'] = '';
$l['error_stop_forum_spam_fetching'] = '';
