<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 09 Aug 2017 09:28:51 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'வணக்கம் உலகமே!';
$l['hello_add'] = 'சேர்த்திடு';
$l['hello_add_message'] = 'விடுகையை சேர்த்திடு';
$l['hello_empty'] = 'விடுகை எதுவும் கிடைக்கவில்லை';
$l['hello_message_empty'] = 'விடுகை காலியாக இருக்கமுடியாது';
$l['hello_done'] = 'ஒரு புதிய விடுகை வெற்றிகரமாக சேர்க்கப்பட்டது.';
