<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 05:57:34 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = 'பயனர் பராமரிப்பு';
$l['s1_desc'] = 'மன்ற கணக்கை பராமரிக்க அடிப்படை வழிமுறைகள்.';
$l['s2_name'] = 'பதிவிடுதல்';
$l['s2_desc'] = 'பதிவிடுதல், பதிலளித்தல் மற்றும்  மன்றத்தின் அடிப்படை பயன்பாடுகள்';
