<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 05:47:22 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'கருத்துக்கள புள்ளிவிபரங்கள்';
$l['new_posts'] = 'மன்றம் புதிய இடுகைகளை கொண்டுள்ளது';
$l['no_new_posts'] = 'மன்றத்தில் புதிய இடுகைகள இல்லை';
$l['forum_locked'] = 'மன்றம் பூட்டப்படுள்ளது';
$l['forum_unapproved_posts_count'] = 'தற்போது இந்த மன்றத்தில் {1} அங்கீகரிக்கப்படாத இடுகைகள் உள்ளன';
$l['forum_unapproved_post_count'] = 'தற்போது இந்த மன்றத்தில் ஒரு அங்கீகரிக்கப்படாத இடுகை உள்ளது';
$l['forum_unapproved_threads_count'] = 'தற்போது இந்த மன்றத்தில் {1} அங்கீகரிக்கப்படாத இழைகள் உள்ளன';
$l['forum_unapproved_thread_count'] = 'தற்போது இந்த மன்றத்தில் ஒரு அங்கீகரிக்கப்படாத இழை உள்ளது';
$l['forumteam'] = 'மன்றக்குழு';
$l['forumstats'] = 'மன்ற புளிவிபரங்கள்';
$l['todays_birthdays'] = 'இன்றைக்கு பிறந்தநாள் காண்போர்';
$l['birthdayhidden'] = 'மறைந்துள்ளது';
$l['quick_login'] = 'விரைவு உள்நுழை:';
$l['index_logout'] = 'வெளியேறு';
$l['private_messages'] = 'தனிப்பட்ட விடுகைகள்';
$l['pms_new'] = 'கடைசி வருகையில் இருந்து {1} புதிய விடுகைகள் உள்ளன';
$l['pms_unread_total'] = '(உங்களுக்கு {1} படிக்காத விடுகைகள் மற்றும் எல்லா தரவுகளிலும் மொத்த்ம் {2} விடுகைகள்  உள்ளன.)';
$l['stats_posts_threads'] = 'நமது உறுப்பினர்கள் மொத்தம் {2} இழைகளில் {1} பதிவுகளை இட்டுள்ளனர்.';
$l['stats_numusers'] = 'நம்முடன் {1} உறுப்பினர்கள் பெயர்பதிந்துள்ளனர்';
$l['stats_newestuser'] = 'நமது அண்மைய உறுப்பபினரான , <b>{1}</b> அவர்களை வரவேற்கிறோம்.';
$l['stats_mostonline'] = 'ஒரே நேரத்தில் அதிகபட்சமாக {1} பயனர்கள் {2} அன்று {3} நேரத்தில் இணைந்திருந்தனர்.';
$l['whos_online'] = 'நிகழ்நிலையில் உள்ளோர்';
$l['complete_list'] = 'முழுப்பட்டியல்';
$l['online_online_plural'] = 'பயனர்கள்';
$l['online_online_singular'] = 'பயனர்';
$l['online_member_plural'] = 'உறுப்பினர்கள்';
$l['online_member_singular'] = 'உறுப்பினர்';
$l['online_anon_plural'] = ' உள்ளனர்';
$l['online_anon_singular'] = ' உள்ளார்';
$l['online_guest_plural'] = 'விருந்தினர்கள்';
$l['online_guest_singular'] = 'விருந்தினர்';
$l['online_note'] = '{1} {2} கடந்த {3} நிமிடங்களில் செயல்பாட்டில் உள்ளனர்({4} {5}, அவர்களில் {6} பேர் மறைந்த நிலையில் {7}, மற்றும்  {8} {9}).';
$l['subforums'] = '<strong>கிளை மன்றங்கள்:</strong>';
