<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 06:01:25 +0000
// --------------------------------------------------------------------------------

$l['error_no_connection'] = 'சேவையகத்தின் மூலம் ஒரு இணைப்பை நிலைநாட்டுவதில் பிழை ஏற்பட்டுள்ளது:';
$l['error_no_message'] = 'விடுகை ஏதும் குறிப்பிடப்படவில்லை.';
$l['error_no_subject'] = 'விடுகைக்கான பொருள் ஏதும் குறிப்பிடப்படவில்லை';
$l['error_no_recipient'] = 'பெறுநர் யாரும் குறிப்பிடப்படவில்லை';
$l['error_not_sent'] = 'PHP mail செயல்பாட்டின் மூலம் அஞ்சல் அனுப்ப முயன்றதில் ஒரு பிழை ஏற்பட்டுள்ளது.';
$l['error_status_missmatch'] = 'சேவையகத்தின் நிலை எதிர்பார்த்த முடிவை தரவில்லை, கீழ்க்கண்டவற்றை திருப்பி அனுப்புகிறது:';
$l['error_data_not_sent'] = 'தரவை சேவையகத்திற்கு அனுப்பு இயலவில்லை:';
$l['error_occurred'] = 'ஒன்று அல்லது அதற்கும் மேற்பட்ட பிழைகள் ஏற்பட்டுள்ளது. தயவுசெய்து தொடர்வதற்கு முன் கீழ்வரும் பிழைகளை சரிசெய்யவும்.<br />';
