<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 09 Aug 2017 11:50:17 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = 'புதிய இழை';
$l['newthread_in'] = '{1}-இல் புதிய இழை';
$l['post_new_thread'] = 'புதிய இழையை பதிவிடு ';
$l['thread_subject'] = 'இழையின் பொருள்';
$l['your_message'] = 'உங்கள் விடுகை';
$l['post_options'] = 'இடுகை தெரிவுகள்:';
$l['options_sig'] = '<b>கையொப்பம்:</b> உங்களுது கையொப்பத்தை உள்ளடக்கு.(பெயர்ப்பதிந்த பயனர்கள் மட்டும்)';
$l['options_emailnotify'] = '';
$l['options_disablesmilies'] = '';
$l['post_thread'] = 'இழையை பதிவிடு';
$l['preview_post'] = 'இடுகையை முன்னோட்டமிடு';
$l['poll'] = 'வாக்கெடுப்பு:';
$l['poll_desc'] = '';
$l['poll_check'] = 'நான் ஒரு வாக்கெடுப்பை பதிவிட விரும்புகிறேன்';
$l['num_options'] = 'தெரிவுகள் எண்ணிக்கை:';
$l['max_options'] = '(அதிகபட்சம்: {1})';
$l['mod_options'] = 'நெறியாளர் தெரிவுகள்';
$l['close_thread'] = '';
$l['stick_thread'] = '';
$l['draft_saved'] = '';
$l['error_post_already_submitted'] = '';
$l['no_prefix'] = 'முன்னொட்டு இல்லை';
$l['forum_rules'] = '{1} - விதிமுறைகள்';
$l['multiquote_external_one'] = '';
$l['multiquote_external'] = '';
$l['multiquote_external_one_deselect'] = 'இந்த இடுகையை தேர்வுநீக்கு';
$l['multiquote_external_deselect'] = 'இந்த இடுகைகளை தேர்வுநீக்கு';
$l['multiquote_external_one_quote'] = 'இந்த இடுகையையும் மேற்கோளிடு';
$l['multiquote_external_quote'] = 'இந்த இடுகைகளையும் மேற்கோளிடு';
$l['redirect_newthread'] = '';
$l['redirect_newthread_poll'] = '';
$l['redirect_newthread_moderation'] = '';
$l['redirect_newthread_unviewable'] = '';
$l['redirect_newthread_thread'] = '';
$l['invalidthread'] = '';
$l['error_stop_forum_spam_spammer'] = '';
$l['error_stop_forum_spam_fetching'] = '';
$l['error_suspendedposting'] = '';
$l['error_suspendedposting_temporal'] = '';
$l['error_suspendedposting_permanent'] = '';
