<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 05:02:46 +0000
// --------------------------------------------------------------------------------

$l['nav_postpoll'] = 'வாக்கெடுப்பை பதிவிடு';
$l['nav_editpoll'] = 'வாக்கெடுப்பை திருத்து';
$l['nav_pollresults'] = 'வாக்கெடுப்பு முடிவுகள்';
$l['edit_poll'] = 'வாக்கெடுப்பை திருத்து';
$l['delete_poll'] = 'வாக்கெடுப்பை நீக்கு';
$l['delete_q'] = 'நீக்கவா?';
$l['delete_note'] = '';
$l['delete_note2'] = '';
$l['question'] = 'கேள்வி:';
$l['num_options'] = 'விருப்பங்கள் எண்ணிக்கை:';
$l['max_options'] = 'அதிகபட்சம்:';
$l['poll_options'] = 'வாக்கெடுப்பு விருப்பங்கள்:';
$l['update_options'] = 'விருப்பங்களை மேம்படுத்து';
$l['poll_options_note'] = '';
$l['options'] = 'விருப்பங்கள்:';
$l['option_multiple'] = '';
$l['option_multiple_maxoptions'] = '';
$l['option_public'] = '';
$l['option_closed'] = '';
$l['poll_timeout'] = '';
$l['timeout_note'] = '';
$l['days_after'] = '';
$l['update_poll'] = '';
$l['option'] = 'விருப்பம்';
$l['votes'] = 'வாக்குகள்:';
$l['post_new_poll'] = 'புதிய வாக்கெடுப்பை பதிவிடு';
$l['days'] = 'நாட்கள்';
$l['poll_results'] = 'வாக்கெடுப்பு முடிவுகள்';
$l['poll_total'] = 'மொத்தம்:';
$l['poll_votes'] = 'வாக்கு(கள்)';
$l['redirect_pollposted'] = '';
$l['redirect_pollpostedmoderated'] = '';
$l['redirect_pollupdated'] = '';
$l['redirect_votethanks'] = '';
$l['redirect_unvoted'] = '';
$l['redirect_polldeleted'] = '';
$l['error_polloptiontoolong'] = '';
$l['error_polloptionsequence'] = '';
$l['error_noquestionoptions'] = '';
$l['error_pollalready'] = 'இழையில் ஏற்கெனவே வாக்கெடுப்பு உள்ளது';
$l['error_nopolloptions'] = '';
$l['error_maxpolloptions'] = '';
$l['error_alreadyvoted'] = '';
$l['error_notvoted'] = '';
$l['error_invalidpoll'] = '';
$l['error_pollclosed'] = '';
$l['poll_time_limit'] = '';
$l['poll_deleted'] = '';
$l['poll_edited'] = '';
