<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 23 Aug 2017 10:08:16 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'வாசல்';
$l['posted_by'] = 'பதித்தது:';
$l['forum'] = 'மன்றம்:';
$l['replies'] = 'பதில்கள்';
$l['no_replies'] = 'பதில்கள் இல்லை';
$l['latest_threads'] = 'அண்மைய இழைகள்';
$l['latest_threads_replies'] = 'பதில்கள்:';
$l['latest_threads_views'] = 'பார்வைகள்:';
$l['latest_threads_lastpost'] = 'கடைசி இடுகை:';
$l['private_messages'] = 'தனிப்பட்ட விடுகைகள்';
$l['pms_received_new'] = '{1}, உங்களுக்கு  <b>{2}</b> படிக்காத விடுகை(கள்) உள்ளன.';
$l['pms_unread'] = 'படிக்காத விடுகைகள்';
$l['pms_total'] = 'மொத்த விடுகைகள்';
$l['search_forums'] = 'மன்றங்களை தேடு';
$l['advanced_search'] = 'மேம்பட்ட தேடல்';
$l['forum_stats'] = 'மன்ற புள்ளிவிபரங்கள்';
$l['num_members'] = 'உறுப்பினர்கள்:';
$l['latest_member'] = 'அண்மைய உறுப்பினர்:';
$l['num_threads'] = 'மன்ற இழைகள்:';
$l['num_posts'] = 'மன்ற இடுகைகள்:';
$l['full_stats'] = 'முழு புள்ளிவிபரங்கள்';
$l['welcome'] = 'நல்வரவு, {1}';
$l['guest'] = 'விருந்தினர்';
$l['guest_welcome_registration'] = 'நீங்கள் நமது வலைதளத்தில் பதிப்பதற்கு முன் <a href=\\"{1}\\">பெயர்ப்பதிவு</a> செய்ய வேண்டும்.';
$l['username'] = 'பயனர்பெயர்';
$l['password'] = 'கடவுச்சொல்';
$l['login'] = 'உள்நுழை';
$l['member_welcome_lastvisit'] = 'கடைசி வருகை:';
$l['since_then'] = 'அதிலிருந்து:';
$l['new_announcements'] = '{1} புதிய அறிவிப்புகள்';
$l['new_announcement'] = 'ஒரு புதிய அறிவிப்பு';
$l['new_threads'] = '{1} புதிய இழைகள்';
$l['new_thread'] = 'ஒரு புதிய இழை';
$l['new_posts'] = '{1} புதிய இடுகைகள்';
$l['new_post'] = 'ஒரு புதிய இடுகை';
$l['view_new'] = 'புதிய இடுகைககளை கண்டிடு';
$l['view_todays'] = 'இன்றைய இடுகைகளை கண்டிடு';
$l['online'] = 'நிகழ்நிலை பயனர்கள்';
$l['online_user'] = 'தற்போது  ஒரு பயனர்  நிகழ்நிலையில் உள்ளார்';
$l['online_users'] = 'தற்போது  <b>{1}</b> பயனர்கள்  நிகழ்நிலையில் உள்ளார்';
$l['online_counts'] = '<b>{1}</b>உறுப்பினர்(கள்) | <b>{2}</b> விருந்தினர்(கள்)';
$l['print_this_item'] = 'இந்த உருப்படியை அச்சிடு';
$l['send_to_friend'] = 'இந்த உருப்படியை நண்பருக்கு அனுப்பு';
$l['latest_announcements'] = 'அண்மைய அறிவிப்புகள்';
$l['portal_disabled'] = 'நீங்கள் வாசல் பயன்பாட்டை பயன்படுத்த முடியாது ஏனெனில் இது நிர்வாகியால் செயலிழக்கப்பட்டுள்ளது.';
