<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 09 Aug 2017 10:46:13 +0000
// --------------------------------------------------------------------------------

$l['forum'] = 'மன்றம்:';
$l['printable_version'] = 'அச்சடிக்கத்தக்க பதிப்பு';
$l['pages'] = 'பக்கங்கள்:';
$l['thread'] = ' இழை:';
