<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 05:28:16 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'நன்றி, உங்களது இந்த இழை வெற்றிகரமாக மதிப்பிடப்பட்டது. நீங்கள் இந்த இழைக்கு திரும்ப அழைத்து செல்லப்படுவீர்கள்.';
$l['error_invalidrating'] = 'நீங்கள் இந்த இழைக்கு செல்லுபடியாகாத மதிப்பீட்டை தேர்ந்தெடுள்ளீர்கள். தயவுசெய்து திரும்ப சென்று மீண்டும் முயற்சிக்கவும்.';
$l['error_alreadyratedthread'] = 'மன்னிக்கவும், இந்த இழையை ஏற்கெனவே மதிப்பிட்டுவிட்டீர்கள்';
$l['error_cannotrateownthread'] = 'மன்னிக்கவும், உங்களது இழையையே நீங்கள் மதிப்பிட முடியாது.';
$l['rating_votes_average'] = '{1} வாக்குகள் - சராசரியாக ஐந்திற்கு {2}';
$l['one_star'] = '5 புள்ளிகளுக்கு 1';
$l['two_stars'] = '5 புள்ளிகளுக்கு 2';
$l['three_stars'] = '5 புள்ளிகளுக்கு 3';
$l['four_stars'] = '5 புள்ளிகளுக்கு 4';
$l['five_stars'] = '5 புள்ளிகளுக்கு 5';
$l['rating_added'] = 'உங்களது மதிப்பீடு சேர்க்கப்பட்டது!';
