<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 09 Aug 2017 09:47:48 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'இந்த இழையை ஒரு நண்பருக்கு அனுப்பு';
$l['send_thread'] = 'நண்பருக்கு அனுப்பு';
$l['recipient'] = 'பெறுநர்:';
$l['recipient_note'] = 'இங்கு உங்களது நண்பர்களின் மின்னஞ்சல் முகவரிகளை கொடுக்கவும்.';
$l['subject'] = 'பொருள்:';
$l['message'] = 'விடுகை:';
$l['error_nosubject'] = 'உங்கள் இழையை அனுப்புவதற்கு விடுகைக்கு ஒரு பொருளை கொடுக்க வேண்டியுள்ளது.';
$l['error_nomessage'] = 'உங்கள் இழையை அனுப்புவதற்கு விடுகைக்கு ஒரு விடுகையை கொடுக்க வேண்டியுள்ளது.';
