<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 09 Aug 2017 17:36:26 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'வாக்கெடுப்பை நீக்கு';
$l['close_thread'] = 'இழையை மூடு';
$l['stick_thread'] = 'இழையை ஒட்டு';
$l['author'] = 'ஆக்கியோன்';
$l['message'] = 'விடுகை';
$l['threaded'] = 'திரிக்கப்பட்ட முறைமை';
$l['linear'] = 'எகபரிமாண முறைமை';
$l['thread_modes'] = 'இழை முறைமைகள்';
$l['next_oldest'] = '';
$l['next_newest'] = '';
$l['view_printable'] = '';
$l['send_thread'] = '';
$l['subscribe_thread'] = '';
$l['unsubscribe_thread'] = '';
$l['add_poll_to_thread'] = 'இந்த இழையுடன் வாக்கெடுப்பை சேர்த்திடு';
$l['moderation_options'] = 'நெறியாளர் தெரிவுகள்:';
$l['delayed_moderation'] = '';
$l['thread_notes'] = '';
$l['open_close_thread'] = 'இழையை திறந்திடு/மூடிடு';
$l['approve_thread'] = 'இழையை அங்கீகரித்திடு';
$l['unapprove_thread'] = 'இழையின் அங்கீகாரம்நீக்கு';
$l['soft_delete_thread'] = '';
$l['restore_thread'] = '';
$l['delete_thread'] = 'இழையை நிரந்திரமாக நீக்கிடு';
$l['delete_posts'] = '';
$l['move_thread'] = '';
$l['stick_unstick_thread'] = '';
$l['split_thread'] = '';
$l['merge_threads'] = '';
$l['remove_redirects'] = '';
$l['remove_subscriptions'] = '';
$l['poll'] = '';
$l['show_results'] = '';
$l['edit_poll'] = '';
$l['public_note'] = '';
$l['total'] = 'மொத்தம்';
$l['vote'] = 'வாக்களித்திடு';
$l['total_votes'] = '{1} வாக்கு(கள்)';
$l['you_voted'] = '* நீங்கள் இந்த உருப்படிக்கு வாக்களித்தீர்கள்.';
$l['poll_closed'] = 'இந்த வாக்கெடுப்பு மூடப்பட்டது.';
$l['poll_closes'] = 'இந்த வாக்கெடுப்பு {1} அன்று மூடப்படும்.';
$l['already_voted'] = 'நீங்கள் இந்த வாக்கெடுப்பில் ஏற்கெனவே வாக்களித்துள்ளீர்கள்.';
$l['undo_vote'] = 'வாக்களித்ததை திரும்ப பெற்றிடு';
$l['quick_reply'] = 'விரைவு பதிலளிப்பு';
$l['message_note'] = '';
$l['signature'] = 'கையொப்பம்';
$l['email_notify'] = 'மின்னஞ்சல் அறிவிக்கை';
$l['disable_smilies'] = 'உணர்ச்சித்திரங்களை முடக்கு';
$l['post_reply'] = 'பதிலை பதிவிடு';
$l['post_reply_img'] = 'பதிலை பதிவிடு';
$l['new_reply'] = 'புதிய பதில்';
$l['search_button'] = 'தேடு';
$l['post_thread'] = 'இழையினை பதிவிடு';
$l['preview_post'] = 'இடுகையை முன்னோட்டமிடு';
$l['rating_average'] = '{1} வாக்கு(கள்) - {2} சராசரி';
$l['rate_thread'] = 'இந்த இழையினை மதிப்பிடு:';
$l['thread_rating'] = 'இழை மதிப்பீடு:';
$l['similar_threads'] = '';
$l['thread'] = 'இழை';
$l['replies'] = 'பதில்கள்';
$l['views'] = 'பார்வைகள்';
$l['lastpost'] = 'கடைசி இடுகை';
$l['messages_in_thread'] = 'இந்த இழையில் உள்ள விடுகைகள்';
$l['users_browsing_thread'] = 'இந்த இழையில் உலாவும் பயனர்கள்:';
$l['users_browsing_thread_guests'] = '{1} விருந்தினர்(கள்)';
$l['users_browsing_thread_invis'] = '{1} மறைந்துள்ள பயனர்(கள்)';
$l['users_browsing_thread_reading'] = 'படிப்பது...';
$l['inline_soft_delete_posts'] = 'இடுகைகளை தற்காலிகமாக நீக்கு';
$l['inline_restore_posts'] = '';
$l['inline_delete_posts'] = '';
$l['inline_merge_posts'] = 'இடுகைகளை ஒன்றிணைத்திடு';
$l['inline_split_posts'] = 'இடுகைகளை பிளவிடு';
$l['inline_move_posts'] = 'இடுகைகளை நகர்த்திடு';
$l['inline_approve_posts'] = 'இடுகைகளை அங்கீகரித்திடு';
$l['inline_unapprove_posts'] = 'இடுகைகளை அங்கீகாரம்நீக்கு';
$l['inline_post_moderation'] = '';
$l['inline_go'] = 'செல்';
$l['clear'] = '';
$l['thread_closed'] = 'இழை மூடப்பட்டது.';
$l['no_subject'] = 'பொருள் இல்லை';
$l['error_nonextnewest'] = '';
$l['error_nonextoldest'] = '';
$l['quickreply_multiquote_selected'] = '';
$l['quickreply_multiquote_now'] = '';
$l['or'] = 'அல்லது';
$l['quickreply_multiquote_deselect'] = 'அவற்றை தேர்வுநீக்கு';
$l['search_thread'] = 'இழையில் தேடு';
$l['enter_keywords'] = '';
$l['view_thread_notes'] = '';
$l['view_all_notes'] = '';
$l['save_changes'] = 'மாற்றங்களை சேமித்திடு';
$l['cancel_edit'] = 'திருத்தங்களை நிராகரித்திடு';
$l['quick_edit_update_error'] = '';
$l['quick_reply_post_error'] = '';
$l['quick_delete_error'] = '';
$l['quick_delete_success'] = '';
$l['quick_delete_thread_success'] = 'இந்த இழை வெற்றிகரமாக நீக்கப்பட்டது.';
$l['quick_restore_error'] = '';
$l['quick_restore_success'] = '';
