<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 04:56:43 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'வாக்கெடுப்பை நீக்கு';
$l['close_thread'] = 'இழையை மூடு';
$l['stick_thread'] = 'இழையை ஒட்டு';
$l['author'] = 'ஆக்கியோன்';
$l['message'] = 'விடுகை';
$l['threaded'] = 'திரிக்கப்பட்ட முறைமை';
$l['linear'] = 'எகபரிமாண முறைமை';
$l['thread_modes'] = 'இழை முறைமைகள்';
$l['next_oldest'] = 'அடுத்த பழையது';
$l['next_newest'] = 'அடுத்த புதியது';
$l['view_printable'] = 'அச்சிடக்கத்தக்க பதிப்பினை கண்டிடு';
$l['send_thread'] = 'இந்த இழையை ஒரு நண்பருக்கு அனுப்பு';
$l['subscribe_thread'] = 'இந்த இழையை பின்தொடர்ந்திடு';
$l['unsubscribe_thread'] = 'இந்த இழையை பின்தொடர்நீக்கு';
$l['add_poll_to_thread'] = 'இந்த இழையுடன் வாக்கெடுப்பை சேர்த்திடு';
$l['moderation_options'] = 'நெறியாளர் தெரிவுகள்:';
$l['delayed_moderation'] = 'தாமதிக்கப்பட்ட மட்டுறுத்தல்';
$l['thread_notes'] = 'இழை குறிப்புகளை கண்டிடு/திருத்து';
$l['open_close_thread'] = 'இழையை திறந்திடு/மூடிடு';
$l['approve_thread'] = 'இழையை அங்கீகரித்திடு';
$l['unapprove_thread'] = 'இழையின் அங்கீகாரம்நீக்கு';
$l['soft_delete_thread'] = 'இழையை தற்காலிகமாக நீக்கு';
$l['restore_thread'] = 'இழையை மீட்டமை';
$l['delete_thread'] = 'இழையை நிரந்திரமாக நீக்கிடு';
$l['delete_posts'] = 'தேர்ந்தெடுக்கப்பட்ட இடுகைகளை நீக்கு';
$l['move_thread'] = 'இழையை நகரத்து/நகலிடு';
$l['stick_unstick_thread'] = 'இழையை ஒட்டு/ஒட்டுநீக்கு';
$l['split_thread'] = 'இழையை பிளவாக்கு';
$l['merge_threads'] = 'இழைகளை ஒன்றிணைத்திடு';
$l['remove_redirects'] = 'மறு அனுப்புகைகளை நீக்கு';
$l['remove_subscriptions'] = 'அனைத்து பின்தொடர்வுகளையும் நீக்கு';
$l['poll'] = 'வாக்கெடுப்பு:  ';
$l['show_results'] = 'முடிவுகளை காட்டு';
$l['edit_poll'] = 'முடிவுகளை திருத்து';
$l['public_note'] = '<b>குறிப்பு:</b> இது ஒரு பொது வாக்கெடுப்பு. நீங்கள் யாருக்கு வாக்களித்துள்ளீர்கள் என்று மற்ற பயனர்கள் காண .இயலும்.
';
$l['total'] = 'மொத்தம்';
$l['vote'] = 'வாக்களித்திடு';
$l['total_votes'] = '{1} வாக்கு(கள்)';
$l['you_voted'] = '* நீங்கள் இந்த உருப்படிக்கு வாக்களித்தீர்கள்.';
$l['poll_closed'] = 'இந்த வாக்கெடுப்பு மூடப்பட்டது.';
$l['poll_closes'] = 'இந்த வாக்கெடுப்பு {1} அன்று மூடப்படும்.';
$l['already_voted'] = 'நீங்கள் இந்த வாக்கெடுப்பில் ஏற்கெனவே வாக்களித்துள்ளீர்கள்.';
$l['undo_vote'] = 'வாக்களித்ததை திரும்ப பெற்றிடு';
$l['quick_reply'] = 'விரைவு பதிலளிப்பு';
$l['message_note'] = 'இந்த விடுகைக்கு உங்களது பதிலை இங்கு தட்டச்சு செய்யுங்கள்.';
$l['signature'] = 'கையொப்பம்';
$l['email_notify'] = 'மின்னஞ்சல் அறிவிக்கை';
$l['disable_smilies'] = 'உணர்ச்சித்திரங்களை முடக்கு';
$l['post_reply'] = 'பதிலை பதிவிடு';
$l['post_reply_img'] = 'பதிலை பதிவிடு';
$l['new_reply'] = 'புதிய பதில்';
$l['search_button'] = 'தேடு';
$l['post_thread'] = 'இழையினை பதிவிடு';
$l['preview_post'] = 'இடுகையை முன்னோட்டமிடு';
$l['rating_average'] = '{1} வாக்கு(கள்) - {2} சராசரி';
$l['rate_thread'] = 'இந்த இழையினை மதிப்பிடு:';
$l['thread_rating'] = 'இழை மதிப்பீடு:';
$l['similar_threads'] = 'தொடர்புடைய இழைகள்...';
$l['thread'] = 'இழை';
$l['replies'] = 'பதில்கள்';
$l['views'] = 'பார்வைகள்';
$l['lastpost'] = 'கடைசி இடுகை';
$l['messages_in_thread'] = 'இந்த இழையில் உள்ள விடுகைகள்';
$l['users_browsing_thread'] = 'இந்த இழையில் உலாவும் பயனர்கள்:';
$l['users_browsing_thread_guests'] = '{1} விருந்தினர்(கள்)';
$l['users_browsing_thread_invis'] = '{1} மறைந்துள்ள பயனர்(கள்)';
$l['users_browsing_thread_reading'] = 'படிப்பது...';
$l['inline_soft_delete_posts'] = 'இடுகைகளை தற்காலிகமாக நீக்கு';
$l['inline_restore_posts'] = 'இடுகைகளை மீட்டமை';
$l['inline_delete_posts'] = 'இடுகைகளை நிரந்திரமாக நீக்கு';
$l['inline_merge_posts'] = 'இடுகைகளை ஒன்றிணைத்திடு';
$l['inline_split_posts'] = 'இடுகைகளை பிளவிடு';
$l['inline_move_posts'] = 'இடுகைகளை நகர்த்திடு';
$l['inline_approve_posts'] = 'இடுகைகளை அங்கீகரித்திடு';
$l['inline_unapprove_posts'] = 'இடுகைகளை அங்கீகாரம்நீக்கு';
$l['inline_post_moderation'] = 'இடுகை மட்டுறுத்தல்:';
$l['inline_go'] = 'செல்';
$l['clear'] = 'துடைத்திடு';
$l['thread_closed'] = 'இழை மூடப்பட்டது.';
$l['no_subject'] = 'பொருள் இல்லை';
$l['error_nonextnewest'] = 'நீங்கள் கண்டு கொண்டிருந்த முந்தை இழையை விட புதிய இழைகள் வேறெதுவும் இல்லை.';
$l['error_nonextoldest'] = 'நீங்கள் கண்டு கொண்டிருந்த முந்தை இழையை விட பழைய இழைகள் வேறெதுவும் இல்லை';
$l['quickreply_multiquote_selected'] = 'நீங்கள் மேற்கோளிட  ஒன்று அல்லது மேற்பட்ட இடுகைகளை தேர்ந்தெடுள்ளீர்கள்.';
$l['quickreply_multiquote_now'] = 'இந்த இடுகைகளை இப்போது மேற்கோளிடு';
$l['or'] = 'அல்லது';
$l['quickreply_multiquote_deselect'] = 'அவற்றை தேர்வுநீக்கு';
$l['search_thread'] = 'இழையில் தேடு';
$l['enter_keywords'] = 'கலைச்சொற்களை கொடுக்கவும்';
$l['view_thread_notes'] = 'இழை குறிப்புகள்';
$l['view_all_notes'] = 'அனைத்து குறிப்புகளையும் கண்டிடு';
$l['save_changes'] = 'மாற்றங்களை சேமித்திடு';
$l['cancel_edit'] = 'திருத்தங்களை நிராகரித்திடு';
$l['quick_edit_update_error'] = 'உங்களது பதிலை திருத்துவதில் பிழை ஏற்பட்டுள்ளது:';
$l['quick_reply_post_error'] = 'உங்களது பதிலை பதிவிடுவதில் பிழை ஏற்பட்டுள்ளது:';
$l['quick_delete_error'] = 'உங்களது பதிலை திருத்துவதில் பிழை ஏற்பட்டுள்ளது:';
$l['quick_delete_success'] = 'இந்த இடுகை வெற்றிகரமாக நீக்கப்பட்டது.';
$l['quick_delete_thread_success'] = 'இந்த இழை வெற்றிகரமாக நீக்கப்பட்டது.';
$l['quick_restore_error'] = 'உங்களது பதிலை  மீட்டமைப்பதில் பிழை ஏற்பட்டுள்ளது:';
$l['quick_restore_success'] = 'இந்த இடுகை வெற்றிகரமாக மீட்டமைக்கப்பட்டது.';
