<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 09 Aug 2017 11:41:59 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'வாக்கெடுப்பை நீக்கு';
$l['close_thread'] = 'இழையை மூடு';
$l['stick_thread'] = 'இழையை ஒட்டு';
$l['author'] = '';
$l['message'] = '';
$l['threaded'] = '';
$l['linear'] = '';
$l['thread_modes'] = '';
$l['next_oldest'] = '';
$l['next_newest'] = '';
$l['view_printable'] = '';
$l['send_thread'] = '';
$l['subscribe_thread'] = '';
$l['unsubscribe_thread'] = '';
$l['add_poll_to_thread'] = '';
$l['moderation_options'] = '';
$l['delayed_moderation'] = '';
$l['thread_notes'] = '';
$l['open_close_thread'] = '';
$l['approve_thread'] = '';
$l['unapprove_thread'] = '';
$l['soft_delete_thread'] = '';
$l['restore_thread'] = '';
$l['delete_thread'] = '';
$l['delete_posts'] = '';
$l['move_thread'] = '';
$l['stick_unstick_thread'] = '';
$l['split_thread'] = '';
$l['merge_threads'] = '';
$l['remove_redirects'] = '';
$l['remove_subscriptions'] = '';
$l['poll'] = '';
$l['show_results'] = '';
$l['edit_poll'] = '';
$l['public_note'] = '';
$l['total'] = '';
$l['vote'] = '';
$l['total_votes'] = '';
$l['you_voted'] = '';
$l['poll_closed'] = '';
$l['poll_closes'] = '';
$l['already_voted'] = '';
$l['undo_vote'] = '';
$l['quick_reply'] = '';
$l['message_note'] = '';
$l['signature'] = '';
$l['email_notify'] = '';
$l['disable_smilies'] = '';
$l['post_reply'] = '';
$l['post_reply_img'] = '';
$l['new_reply'] = '';
$l['search_button'] = '';
$l['post_thread'] = '';
$l['preview_post'] = '';
$l['rating_average'] = '';
$l['rate_thread'] = '';
$l['thread_rating'] = '';
$l['similar_threads'] = '';
$l['thread'] = '';
$l['replies'] = '';
$l['views'] = '';
$l['lastpost'] = '';
$l['messages_in_thread'] = '';
$l['users_browsing_thread'] = '';
$l['users_browsing_thread_guests'] = '';
$l['users_browsing_thread_invis'] = '';
$l['users_browsing_thread_reading'] = '';
$l['inline_soft_delete_posts'] = '';
$l['inline_restore_posts'] = '';
$l['inline_delete_posts'] = '';
$l['inline_merge_posts'] = '';
$l['inline_split_posts'] = '';
$l['inline_move_posts'] = '';
$l['inline_approve_posts'] = '';
$l['inline_unapprove_posts'] = '';
$l['inline_post_moderation'] = '';
$l['inline_go'] = '';
$l['clear'] = '';
$l['thread_closed'] = '';
$l['no_subject'] = '';
$l['error_nonextnewest'] = '';
$l['error_nonextoldest'] = '';
$l['quickreply_multiquote_selected'] = '';
$l['quickreply_multiquote_now'] = '';
$l['or'] = '';
$l['quickreply_multiquote_deselect'] = '';
$l['search_thread'] = '';
$l['enter_keywords'] = '';
$l['view_thread_notes'] = '';
$l['view_all_notes'] = '';
$l['save_changes'] = '';
$l['cancel_edit'] = '';
$l['quick_edit_update_error'] = '';
$l['quick_reply_post_error'] = '';
$l['quick_delete_error'] = '';
$l['quick_delete_success'] = '';
$l['quick_delete_thread_success'] = '';
$l['quick_restore_error'] = '';
$l['quick_restore_success'] = '';
