<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Fri, 11 Aug 2017 00:49:27 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'மன்றக்குழு';
$l['forum_team'] = 'மன்றக்குழு';
$l['moderators'] = 'நெறியாளர்கள்';
$l['username'] = 'பயனர் பெயர்';
$l['lastvisit'] = 'கடைசி வருகை';
$l['email'] = 'மின்ன்னஞ்சல்';
$l['pm'] = 'த.வி.';
$l['mod_forums'] = 'மன்றங்(கள்​)';
$l['online'] = 'நிகழ்நிலை';
$l['offline'] = 'அகல்நிலை';
$l['away'] = 'தொலைவில்';
$l['group_leaders'] = 'தலைவர்(கள்)';
$l['group_members'] = 'உறுப்பினர்(கள்)';
$l['no_members'] = 'இந்த குழுவில் உறுப்பினர்கள் இல்லை';
$l['error_noteamstoshow'] = 'மன்ற அலுவலர்கள் காண்பிப்பதற்கு யாருமில்லை.';
