<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Thu, 10 Aug 2017 05:53:47 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'கருத்துகள புள்ளிவிபரங்கள்';
$l['stats_disabled'] = 'நிர்வாகியால் இந்த பக்கம் செயலிழக்கப்படடுள்ளதால் நீங்கள் புள்ளிவிபர பக்கத்தை காண இயலாது.';
$l['board_stats'] = 'கருத்துகள புள்ளிவிபரங்கள்';
$l['none'] = 'ஏதுமில்லை';
$l['totals'] = 'மொத்தங்கள்';
$l['averages'] = 'சராசரிகள்';
$l['posts'] = 'இடுகைகள்:';
$l['threads'] = 'இழைகள்:';
$l['members'] = 'உறுப்பினர்கள்:';
$l['ppd'] = 'நாள் வீதம் இடுகைகள்:';
$l['tpd'] = 'நாள் வீதம் இழைகள்:';
$l['mpd'] = 'நாள் வீதம் உறுப்பினர்கள்:';
$l['ppm'] = 'உறுப்பினர் வீதம் இடுகைகள்:';
$l['tpm'] = 'உறுப்பினர் வீதம் இழைகள்:';
$l['rpt'] = 'இழைகள் வீதம் பதில்கள்:';
$l['no_posts'] = 'இல்லை';
$l['general'] = 'பொது';
$l['newest_member'] = 'அண்மைய உறுப்பினர்:';
$l['members_posted'] = 'இடுகை பதிந்துள்ள உறுப்பினர்கள்:';
$l['todays_top_poster'] = 'இன்றைய முதன்மை இடுகை பதிப்பாளர்: <b>{1}</b> (<b>{2}</b> இடுகைகள்)';
$l['popular_forum'] = 'மிகவும் பிரபலமான மன்றம்: <b>{1}</b> (<b>{2}</b> இடுகைகள், <b>{3}</b> இழைகள்)';
$l['most_popular'] = 'மிகவும் பிரபலமான...';
$l['most_replied_threads'] = 'அதிகபட்ச பதில்களையுடைய இழைகள்';
$l['most_viewed_threads'] = 'அதிகபட்ச பார்வையிடப்பட்ட இழைகள்';
$l['not_enough_info_stats'] = 'மன்னிக்கவும், இந்த கருத்துகளத்தில் புள்ளிவிபரங்களை உருவாக்க போதிய தகவல்கள் இல்லை. புள்ளிவிபரங்களை உருவாக்குமுன் குறைந்தப்பட்சம் ஒரு உறுப்பினர் மற்றும் ஒரு இடுகை தேவைப்படுகிறது.';
$l['replies'] = 'பதில்கள்';
$l['views'] = 'பார்வைகள்';
$l['top_referrer'] = 'முதன்மை பரிந்துரையாளர்: <strong>{1}</strong> (<strong>{2}</strong> பரிந்துரைகள்)';
