<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Fri, 11 Aug 2017 00:37:14 +0000
// --------------------------------------------------------------------------------

$l['all_forums'] = 'அனைத்து மன்றங்கள்';
$l['forum'] = 'மன்றம்:';
$l['posted_by'] = 'பதித்தவர்:';
$l['on'] = 'பதித்த நாள்';
$l['portal'] = 'வாசல்';
