<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Tamil (India)
// Author of the language pack : Shiva
// Language pack translators website : https://surangam.net/
// Compatible version of MyBB : 1812
// Last edited in MyBB Editor by : Surangam
// Last edited date : Wed, 23 Aug 2017 09:49:20 +0000
// --------------------------------------------------------------------------------

$l['nav_profile'] = 'பயனர் {1} சுயவிவரம்';
$l['nav_warning_log'] = 'எச்சரிக்கை செயற்பதிவு';
$l['nav_add_warning'] = 'பயனரை எச்சரித்திடு';
$l['nav_view_warning'] = 'எச்சரிக்கை விவரங்கள்';
$l['warning_for_post'] = '.. இடுகை:';
$l['already_expired'] = 'காலாவதியானது';
$l['details_username'] = 'பயனர் பெயர்';
$l['warning_active'] = 'செயல்பாட்டில் உள்ளது';
$l['warning_revoked'] = 'திரும்பப்பெறப்பட்டது';
$l['warning_log'] = 'எச்சரிக்கை செயற்பதிவு';
$l['warning'] = 'எச்சரிக்கை';
$l['issued_by'] = 'வழங்கியவர் :';
$l['date_issued'] = 'வழங்கிய நாள்';
$l['expiry_date'] = 'காலாவதியாவது';
$l['active_warnings'] = 'செயல்பாட்டில் உள்ள எச்சரிக்கைகள்';
$l['expired_warnings'] = 'காலாவதியான எச்சரிக்கைகள்';
$l['warning_points'] = '({1} புள்ளிகள்)';
$l['no_warnings'] = 'இந்த பயனர் எந்த எச்சரிக்கையையும் பெறவில்லை அல்லது அனைத்து எச்சரிக்கைகளும் நீக்கபட்டன.';
$l['warn_user'] = 'பயனரை எச்சரித்திடு';
$l['post'] = 'இடுகை:';
$l['warning_note'] = 'நிர்வாகக்குறிப்புகள்:';
$l['details_warning_note'] = 'நிர்வாகக்குறிப்புகள்';
$l['warning_type'] = 'எச்சரிக்கை வகை:';
$l['custom'] = 'தனிப்பட்ட காரணம்';
$l['reason'] = 'காரணம்:';
$l['points'] = 'புள்ளிகள்:';
$l['details_reason'] = 'காரணம்';
$l['warn_user_desc'] = 'ஒன்றுக்கு மேற்பட்ட விதிகளை மீறி இருந்தால் இங்கு இந்த பயனரின் எச்சரிக்கை அளவை அதிகரிக்கலாம்.';
$l['send_pm'] = 'பயனருக்கு தெரிவித்துவிடு:';
$l['send_user_warning_pm'] = '';
$l['send_pm_subject'] = '';
$l['warning_pm_subject'] = '';
$l['send_pm_message'] = '';
$l['warning_pm_message'] = '';
$l['send_pm_options'] = '';
$l['send_pm_options_anonymous'] = '';
$l['expiration_never'] = '';
$l['expiration_hours'] = '';
$l['expiration_days'] = '';
$l['expiration_weeks'] = '';
$l['expiration_months'] = '';
$l['redirect_warned_banned'] = '';
$l['redirect_warned_suspended'] = '';
$l['redirect_warned_moderate'] = '';
$l['redirect_warned_pmerror'] = '';
$l['redirect_warned'] = '';
$l['error_warning_system_disabled'] = '';
$l['error_cant_warn_group'] = '';
$l['error_invalid_user'] = '';
$l['details'] = '';
$l['view'] = '';
$l['current_warning_level'] = '';
$l['warning_details'] = '';
$l['revoke_warning'] = '';
$l['revoke_warning_desc'] = '';
$l['warning_is_revoked'] = '';
$l['revoked_by'] = '';
$l['date_revoked'] = '';
$l['warning_already_revoked'] = '';
$l['no_revoke_reason'] = '';
$l['redirect_warning_revoked'] = '';
$l['result'] = '';
$l['result_banned'] = '';
$l['result_suspended'] = '';
$l['result_moderated'] = '';
$l['result_period'] = '';
$l['result_period_perm'] = '';
$l['hour_or_hours'] = '';
$l['day_or_days'] = '';
$l['week_or_weeks'] = '';
$l['month_or_months'] = '';
$l['expires'] = '';
$l['new_warning_level'] = '';
$l['error_cant_warn_user'] = '';
$l['existing_post_warnings'] = '';
